spring:
  datasource:
    port: 5432
    host: epruizhw0388
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/hardinv'
    username: HIapp
    password: hardcoded2014

  security:
    user:
      password: 123

  cache:
    cache-names: settings
    caffeine:
      spec: expireAfterAccess=5s
